[package]
name = "sdk-uniffi"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

include = [
    "pyproject.toml",
    "src",
    "uniffi.toml",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lexe"
crate-type = ["cdylib"]
doc = false

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi_bindgen.rs"
required-features = ["bindgen"]

[dependencies]
# --- LEXE --- #

# NOTE: To ensure `lexe` exposes all types and sub-crates needed for SDK
# implementors, this crate should *only* depend on `lexe`.
# TODO(max): Clean up these dependencies; upstream the
# `wait_for_payment_completion` logic, add re-exports and crate exports if
# needed.
common = { path = "../common" }
lexe = { path = "../lexe" }
lexe-api-core = { path = "../lexe-api-core" }
lexe-std = { path = "../lexe-std" }
node-client = { path = "../node-client", default-features = false }

# --- WORKSPACE --- #

anyhow.workspace = true
secrecy.workspace = true
tokio.workspace = true
uniffi = { workspace = true, features = ["tokio"] }

# --- OPTIONAL --- #

[features]
# TODO(phlip9): no default features once this commit makes it into next
# maturin-v1.10.3: <https://github.com/PyO3/maturin/commit/7de7bc8d5214d16ec3b3fe070580f6383701b98a>
default = ["bindgen"]
bindgen = ["uniffi/cli", "uniffi/build"]
