[package]
name = "sdk"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lexe"
crate-type = ["cdylib"]

[dependencies]
# --- LEXE --- #

# --- WORKSPACE --- #

uniffi.workspace = true

# --- OPTIONAL --- #
