[project]
name = "lexe"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[project.urls]
homepage = "https://lexe.app" # TODO(phlip9): point to SDK docs site
repository = "https://github.com/lexe-app/lexe-public/tree/master/sdk"
changelog = "https://github.com/lexe-app/lexe-public/releases"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "maturin>=1.10,<2.0" # keep in sync with below
]

[build-system]
requires = ["maturin>=1.10,<2.0"] # keep in sync with above
build-backend = "maturin"

[tool.maturin]
python-source = "python"
bindings = "uniffi"

[tool.pytest.ini_options]
asyncio_mode = "auto"
